import { GoogleTagManager } from "@next/third-parties/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManager gtmId="GTM-MVC4G9ZN" />
      </head>
      <body>{children}</body>
    </html>
  );
}
